// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCxmWrsUp-HfQ_o8SUmhWRifLUoats44I',
    appId: '1:376225930229:android:204673abc368dd0c5f1ebc',
    messagingSenderId: '376225930229',
    projectId: 'pexels-view',
    storageBucket: 'pexels-view.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Bc6mlhnPAzcz1rly5bbnGYOxNKYtoBM',
    appId: '1:376225930229:ios:0c746b2fa262ecce5f1ebc',
    messagingSenderId: '376225930229',
    projectId: 'pexels-view',
    storageBucket: 'pexels-view.appspot.com',
    androidClientId: '376225930229-30avdvkkea7g1l7e3j22924ps7cdt5bg.apps.googleusercontent.com',
    iosClientId: '376225930229-npiarmbhvlqectgajhgqgsj989qvodts.apps.googleusercontent.com',
    iosBundleId: 'link.gamecafe.eat',
  );
}
